### ISSUE TITLE
`Tab` key in Configuration dialog moves focus to pseudocode view

### ISSUE THREAD

**Issue by mborgerson** [binsync/binsync#187]
* Running on Ubuntu 22.04, IDA 8.0
* Open configuration view, click on 'User name' text box, enter user name
* Press <kbd>Tab</kbd> to move to Git repo field. Focus is not moved to next field, but instead moves to IDA main window  Pseudocode view
   * This is the expected behavior when in the main window, but unexpected when entering input in a dialog 
* Interestingly, <kbd>Shift</kbd>+<kbd>Tab</kbd> does cycle through dialog controls as expected

**Comment by mahaloz** [comment]
Related to #190, see the discussion there for more info.
