### ISSUE TITLE
Setuptools `develop` command class now called with newest versions

### ISSUE THREAD

**Issue by zwimer** [binsync/binsync#226]
### Description

In `setup.py` you override the `develop` cmdclass; with newer versions of setuptools; editable wheels are build and `develop` is not invoked.

I.e. I believe `setup.py` may not be compatible with the newest versions of setuptools.

### Steps to reproduce the bug

`pip install` with the newest pip and setuptools.

### Environment

Main: https://github.com/binsync/binsync/commit/9b840ea3f866aa89c639425bd3ac9ae032212445

**Comment by zwimer** [comment]
You can still manually call `python setup.py develop` though.

**Comment by zwimer** [comment]
`angr` hit a similar problem: https://github.com/angr/angr/issues/3487 and pinned lower versions: https://github.com/angr/angr/pull/3484

**Comment by mahaloz** [comment]
This seems to have resolved itself.
