### ISSUE TITLE
Binary Ninja Plugin Manager Support

### ISSUE THREAD

**Issue by mahaloz** [binsync/binsync#237]
### Description

Add BinSync to the Binay Ninja Plugin Manager

**Comment by mahaloz** [comment]
## Ready Release
Alright, BinSync is ready for installation on Release [v3.1.0](), which has the same tag version. The Binary Ninja code entry point is located in the [plugins/binja_binsync](https://github.com/binsync/binsync/tree/main/plugins/binja_binsync) folder. The files in this folder may change in the future, but the location will stay the same.

**Comment by psifertex** [comment]
Unfortunately I think you ran afoul of some bad or old documentation. We've migrated away from the [old](https://github.com/binsync/binsync/blob/main/plugins/binja_binsync/plugin.json#L19) pip dependencies to now simply [using](https://docs.binary.ninja/dev/plugins.html#creating-the-plugin:~:text=If%20you%20have%20python%20dependencies%2C%20create%20a%20requirements.txt%20listing%20any%20python%20dependencies.) a `requirements.txt` file instead. 

Sorry about that! If you can let me know where you saw the old syntax I've been trying to remove it from all our examples/documentation.

**Comment by psifertex** [comment]
No worries, thanks for the quick turn on this in general. I'm working on something unrelated which will delay the plugin manager update shortly but as soon as I get that resolved I'll come back here and confirm.

**Comment by mahaloz** [comment]
@psifertex Sorry to update things one more time, but I've bumped the release one more time to [v3.2.3](https://github.com/binsync/binsync/releases/tag/v3.2.3), which has changed the location of the Binary Ninja stub (decided to take inspiration from the Lighthouse plugin layout). The new location is here: https://github.com/binsync/binsync/tree/main/decompiler_stubs/binja_binsync. Thanks again!

**Comment by psifertex** [comment]
Oh! This is the update you mean. Yeah, no worries, you don't have to let me know anymore. Once we add a plugin, we add it to our tracked plugins and we see releases automatically. Feel free to close this whenever.

**Comment by mahaloz** [comment]
This landed :).
