### ISSUE TITLE
Installing BinSync seems to interfere with Qt usage in other plugins (e.g. snippets editor)

### ISSUE THREAD

**Issue by alexrp** [binsync/binsync#286]
### Description

Installing BinSync via Binary Ninja's plugin manager appears to interfere with Qt usage in other plugins:

```
Failed to import python plugin: official/Vector35_snippets: DLL load failed while importing QtCore: The specified procedure could not be found.
Failed to load plugin: Vector35_snippets
```

(I'm not sure if there's a way to get a more... actionable error message here.)

### Steps to reproduce the bug

Just for good measure, I ensured that BN is using its bundled Python for everything, and then nuked all installed plugins and site-packages. After that, I installed just the snippets editor plugin and the BinSync plugin.

### Environment

Binary Ninja 3.5.4311-dev Personal (ff27871c)

**Comment by alexrp** [comment]
Also, oddly, just installing BinSync via the plugin manager (and nothing else) on a clean BN gets me:

```
[!] BinSync is not installed, please `pip install binsync` for THIS python interpreter
```

Isn't that literally what the plugin manager does?

**Comment by alexrp** [comment]
If I had to hazard a total guess here, it seems like BinSync's PySide6 dependency (resulting in 6.5.1) might be what breaks things since BN ships with its own PySide6 (6.4.3). But I'm mostly clueless on Python stuff, so what do I know. 🤷

**Comment by mahaloz** [comment]
@alexrp I think you're right on the money with your guess. The only new thing on the BinSync side in the last few updates has been our addition of the PySide6 requirement. This is a problem, is seems, for Binja. The best solution would probably be to figure out on the Binja side what PySide6 version is allowed. Otherwise, we may need to do some dependency management and remove PySide6 while adding it as a special dependency for the Ghidra installs (which requires 6).

**Comment by mahaloz** [comment]
> Also, oddly, just installing BinSync via the plugin manager (and nothing else) on a clean BN gets me this after restarting BN:
> 
> ```
> [!] BinSync is not installed, please `pip install binsync` for THIS python interpreter
> ```
> 
> Isn't that literally what the plugin manager does? Also, it's very strange that BinSync appears to be working fine before I restart BN, but not after.

This could be better. This gets printed if ANY import error happens. If I had to guess, it tried to import something PySide-specific. This installer in Binja actually does two things:
1. Copies the stub into Binja
2. Pip installs `binsync`, which could potentially fail

If BinSync is installed correctly, any ImportError could still trigger this.

**Comment by alexrp** [comment]
I can try to figure out which PySide6 version works on the BN side, but as I mentioned, Python is not my forte. Is there an easy way that I can install a specific PySide6 version for BinSync?

**Comment by alexrp** [comment]
OK, well, taking the cave man approach of just nuking PySide6 and Shiboken packages from my BN user site-packages directory seems to work, at least.

**Comment by alexrp** [comment]
Next, trying to install the PySide6 version used by BN like so:

```
C:\Program Files\Vector35\BinaryNinja\plugins\python
$ ./python -m pip install  --upgrade --isolated PySide6==6.4.3 -t "C:\Users\alex\AppData\Roaming\Binary Ninja\python310\site-packages"
```

Once again breaks things. So it seems the dependency is a problem regardless of version... 🤔

**Comment by alexrp** [comment]
Just confirming on my end that after #289, things are working.
