### ISSUE TITLE
Control panel as a sidebar widget in Binary Ninja

### ISSUE THREAD

**Issue by alexrp** [binsync/binsync#287]
### Description

Right now, it seems that I can only dock the control panel widget at the top or bottom of Binary Ninja's UI. Neither is ideal given the layout of the widget. (I actually also can't figure out how to dock it on the right side again after I undocked it. Could there be a bug here?)

For me, the ideal would be if the control panel was just a widget on the sidebar like any other.

**Comment by mahaloz** [comment]
@alexrp I really like the idea of this being another sidebar widget. That would be super cool! Would you happen to know any other plugin that exists that does this?

Also, redocking should just happen... we don't actually control that though. Through the Binja API we just as for a panel.

**Comment by alexrp** [comment]
> Would you happen to know any other plugin that exists that does this?

The debugger plugin does this, I think: https://github.com/Vector35/debugger

I don't know the exact details of how it's achieved though.

> Also, redocking should just happen... we don't actually control that though. Through the Binja API we just as for a panel.

Yeah, it's a bit odd. BN lets me dock the control panel at the top and bottom of the window as you'd expect, but not on the right side at all. 🤔

**Comment by alexrp** [comment]
> Yeah, it's a bit odd. BN lets me dock the control panel at the top and bottom of the window as you'd expect, but not on the right side at all. 🤔

Following up on this point: The control panel seems to have redocked itself to the right side after restarting BN.

**Comment by mahaloz** [comment]
Asked around, so it looks like it can be done and here is some nice reference code:
https://github.com/elbiazo/calltree/blob/48071ef1394d437edb76a134ae838c1528cdb0ba/init.py#L242

For us, the trickest part will be dealing with what happens with the widget is closed, since I don't know how that works yet.
