### ISSUE TITLE
An easy way to temporarily disconnect from a repo (or pause syncing)

### ISSUE THREAD

**Issue by alexrp** [binsync/binsync#292]
### Description

It would be nice if there was an easy way to temporarily disconnect from a BinSync repo, or at least pause syncing.

Sometimes I'll want to do some experimental scripting in BN that may have wide-reaching effects on the BNDB. But if I find that it didn't quite work out, I'll just throw out the changes without even saving the BNDB. But if BinSync is running, it will of course pick up those changes.

### Alternatives

Restarting the decompiler and not connecting to the BinSync repo. But this is not so desirable for very large binaries as loading can take several minutes.

**Comment by mahaloz** [comment]
@alexrp I like this idea as well. Could you clarify some other things though? When you say `pause`, do you just want to stop committing? Or do you want to stop _everything_, like pulling in the background? 

Right now I think it could be pretty trivial to add a `Disable auto-commit` in the `Utils` tab. This would stop changes you made being propagated into BinSync, but it would allow `pulling` each branch in the background to still occur.

**Comment by alexrp** [comment]
I *think* pulling should be fine. It would mainly be about pausing pushing.

**Comment by mahaloz** [comment]
@alexrp I think you actually mean pausing committing right? Since pushing happening is meaningless if no changes get committed to the current state.

**Comment by alexrp** [comment]
Hrm, I guess so, assuming committing and pushing are separate operations in BinSync rather than being rolled into one.

**Comment by mahaloz** [comment]
@alexrp if you have the ability to run a cloned instance, you should checkout to #299 and let me know if that works for you. If you can't I'll probably just merge into main at some point this weekend.
