### ISSUE TITLE
Comments not auto-commiting in Binja

### ISSUE THREAD

**Issue by Maxou56800** [binsync/binsync#336]
### Description

When I update something in Binary Ninja, like add a comment on a random line, I get some logs about changes, but no effects.

```python
[0:6125121294342392614 Undo debug] UNDO: Add action Comment in function sub_2150 at 0x215f to entry d947a3c2-806c-419a-ac8e-bbbe74b14f88
[0:6125121294342392614 Undo debug] UNDO: Commit d947a3c2-806c-419a-ac8e-bbbe74b14f88
[0:6125121294342392614 Undo debug] UNDO: Commit entry d947a3c2-806c-419a-ac8e-bbbe74b14f88
```

or

```python
[0:6125121294342392614 Undo debug] UNDO: Add action Defined name newfunctionname at 0x2150 to entry 3a98494a-dcc7-44cd-93f4-6c887b14ba05
[0:6125121294342392614 Undo debug] UNDO: Commit 3a98494a-dcc7-44cd-93f4-6c887b14ba05
[0:6125121294342392614 Undo debug] UNDO: Commit entry 3a98494a-dcc7-44cd-93f4-6c887b14ba05
```

When I check the git information, nothing appears: 

```bash
$ cd /path/to/reverse_project/
$ git checkout binsync/myusername
$ git diff
$ # No differences...
$ git log

commit 9c68782704b55aaa60ba129b201215e0f3fcdfc7 (HEAD -> binsync/myusername, origin/binsync/myusername)
Author: user <user@mail.com>
Date:   Wed Sep 13 13:37:00 2023 +0200

    User created

commit 0c388f47fe7938cd690ae9669340d2e6acb8afeb (origin/binsync/__root__, binsync/__root__)
Author: user <user@mail.com>
Date:   Wed Sep 13 13:37:00 2023 +0200

    Root commit
```

### Steps to reproduce the bug

1) Start binja
2) Open a sample
2) Plugins>Binsync configure..
3) Configure and open a existing git folder
4) Do an update like add a comment

### Environment

OS: Linux
Binja: 3.5.4525-dev (5c6bbf2c)
Binsync plugin version: 3.13.1

### Additional context

Thank you for this very interesting project!

**Comment by mahaloz** [comment]
@Maxou56800 just to confirm, this is after a fresh run right? If BinSync crashes in something else (like your earlier made issues), then you try to do anything else, it will likely fail.

**Comment by Maxou56800** [comment]
Yes I was using the same configuration, same sample. The problem happens as soon as I do any kind of manipulation. So yes, as soon as I open a sample.

**Comment by mahaloz** [comment]
@Maxou56800 this may be a comment commit bug. Did you try renaming a function? Can you see if that operations triggers a commit?

**Comment by Maxou56800** [comment]
Yes it's a comment bug. Renaming a function is working well.

**Comment by Exiled1** [comment]
Any clues as to why this is happening? I might be able to take a look

**Comment by mahaloz** [comment]
Haven't done any debugging, so I'd have to guess it's coming from the data monitor or lack there of

**Comment by Exiled1** [comment]
Alright, sounds good, I'll do some quick debugging checks then

**Comment by mahaloz** [comment]
Closed in https://github.com/binsync/binsync/pull/347
