### ISSUE TITLE
Large function changes take hours to propagate

### ISSUE THREAD

**Issue by agnosticlines** [binsync/binsync#349]
### Description

Mentioned this to mahaloz on Slack, here's what happened.

I have two binaries, one with symbols, one without, I was using Diaphora to port the symbols over to the newer build without symbols, I right clicked on 100 or so of the best/possible matches and imported them into the database, I kept doing this until I had about 1000 symbols imported, the database reflected this, I then went away from my computer and came back and saw commits were still being added to the repo hours after I imported them to the database, this went on for roughly 6 hours until they stopped, I verified this wasn't just a UI quirk, the files were being created and commited hours after initial import.

### Steps to reproduce the bug

1. Diff two binaries using diaphora
2. Select 100+ or so entries and import/apply them

### Environment

System Information: Windows 11 ARM64 running Git for Windows on IDA Pro 8.3

**Comment by mahaloz** [comment]
@agnosticlines, so I think this may be fixed in #347, which changes how batch committing works, among other things. I'll ping you again when it gets merged, which should be in the next 2 weeks or so.

**Comment by mahaloz** [comment]
Closed in https://github.com/binsync/binsync/pull/347
