### ISSUE TITLE
Function force push from UI in Binary Ninja throws exception

### ISSUE THREAD

**Issue by VisualEhrmanntraut** [binsync/binsync#357]
### Description

```
[Default] Traceback (most recent call last):
[Default]   File "/Users/visual/Library/Application Support/Binary Ninja/python310/site-packages/binsync/ui/control_panel.py", line 33, in <lambda>
[Default]     menu.addAction(f"Force Push {ctx_name}@{hex(ctx_addr)}", lambda : self.controller.force_push_function(ctx_addr))
[Default] AttributeError: 'BSController' object has no attribute 'force_push_function'. Did you mean: 'force_push_functions'?
```

### Steps to reproduce the bug

Go to a function. Open the BinSync dock. Right click the function at the bottom (next to "Connected"). Click force push. Observe that nothing happens, and error is thrown in log.

### Environment

Binary Ninja 4.1.5014-dev Personal (349de5a9)
macOS 14.4.1 (23E224)

**Comment by VisualEhrmanntraut** [comment]
@mahaloz should be easy to fix, just a typo from what I can tell :)

**Comment by mahaloz** [comment]
Fixed in https://github.com/binsync/binsync/commit/48ecdd44bacf930cebf7df7286ad4288e9bbd6e3, on version `4.0.5`
