### ISSUE TITLE
CI not testing oldest supported python version

### ISSUE THREAD

**Issue by twizmwazin** [binsync/binsync#366]
### Description

Right now the CI tests on version 3.11. Thus, it guarantees nothing about correctness or compatibility for versions less than 3.11.

### Environment

GitHub actions CI

### Additional context

If you only run tests on a single python version, the oldest supported version is probably the best idea. This is what angr does. While there can be compatibility issues on newer versions, they are generally less and more obvious than the reverse. Of course, if you want to be thorough, consider running tests for each supported version.

Related: #365

**Comment by mahaloz** [comment]
#367 addresses this PR, but, unfortunately, wouldn't have caught the bug mentioned in #365 because we don't have an code coverage for the IDA code, since we need a private CI for that.

**Comment by twizmwazin** [comment]
A possible option you could use that may help is using a linter. `ruff` I believe will report if syntax is invalid for the minimum supported python version, without needing to actually import or run the code.
