### ISSUE TITLE
Docs need to be updated for current version

### ISSUE THREAD

**Issue by 5angjun** [binsync/binsync#371]
### Question

Hello, I'm sangjun who very interested in this project.

However, I want to use this tool in windows 11 with ida 7.7.
But i failed because of this errors.

So i follow the Manual install, but i can't find the `decompiler_stubs/ida_binsync.py` files in current version.
But can find in older version. I think you need to update Docs fit for current version.
 
https://binsync.net/docs/install/#manual-install

![image](https://github.com/binsync/binsync/assets/76202024/0f8b0ee9-aa68-42a7-9354-a4642a2c1674)

![image](https://github.com/binsync/binsync/assets/76202024/f131aaee-8a55-4312-b408-e0702c533fb5)

And Can you give some tips for install BinSync to windows11?

**Comment by ltfish** [comment]
I think the problem is that you are using Python 3.6 while BinSync requires Python >= 3.8. Please update your Python locally.

**Comment by 5angjun** [comment]
It works when i update python thanks!!
