### ISSUE TITLE
Cannot reopen panel once closed in angr management.

### ISSUE THREAD

**Issue by burhanr13** [binsync/binsync#381]
### Description

after closing the control panel via the x button or Toggle Panel menu option, neither the Start binsync or toggle panel menu options will not reopen the panel.

### Steps to reproduce the bug

In angr management enable binsync, then open the panel via toggle panel or start binsync, close via toggle panel or close button, then attempt to reopen with the menu options, and it will not reopen.

### Environment

python 3.10, binsync 4.2.1, angr management 9.2.106

**Comment by mahaloz** [comment]
Hmmm I see. I think someone else reported this issue in the past and dropped investigation.

@frqmod any chance I can get you to emerge from the woodwork and debug this, since you own this code 😁?
